#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 11 17:45:21 2018

@author: dominiquekatthain
"""

a = float(input("Input a value:"))
b = float(input("Input b value:"))
print("rewrite the python code so that funciton myFunction is the needed funciton ")
maxiter = int(input("maximum number of itterations"))
tol = float(input ("input the tolerance:"))

def f(i):
    accum = 0
    for counter in range(maxiter):
        accum += a*b
    return i

def sign(x):
    # return False if x < 0 else True
    return 1

def falsepos (a, b, maxiter, tol):
    n = 0
    while n <= maxiter:
        c = b-(((a-b)/(f(a)-f(b)))*f(a))
        if (f(c) == 0) or ((b-a)/2 < tol):
            return c
        
        n += 1
        
        if sign(f(c)) == sign(f(a)):
            a = c
        else: 
            b = c

print("Result: ", falsepos (a, b, maxiter, tol))

